// user
export const GET_SIGNIN_USER_SUCCESS = "GET_SIGNIN_USER_SUCCESS"
export const GET_SIGNIN_USER_REQUEST = "GET_SIGNIN_USER_REQUEST"
export const GET_SIGNIN_USER_ERROR = "GET_SIGNIN_USER_ERROR"

export const GET_CLINIC_LIST_REQUEST = "GET_CLINIC_LIST_REQUEST"
export const GET_CLINIC_LIST_SUCCESS = "GET_CLINIC_LIST_SUCCESS"
export const GET_CLINIC_LIST_ERROR = "GET_CLINIC_LIST_ERROR"

export const GET_HOLIDAY_LIST_REQUEST = "GET_HOLIDAY_LIST_REQUEST"
export const GET_HOLIDAY_LIST_SUCCESS = "GET_HOLIDAY_LIST_SUCCESS"
export const GET_HOLIDAY_LIST_ERROR = "GET_HOLIDAY_LIST_ERROR"

export const GET_PATIENT_LIST_REQUEST = "GET_PATIENT_LIST_REQUEST"
export const GET_PATIENT_LIST_SUCCESS = "GET_PATIENT_LIST_SUCCESS"
export const GET_PATIENT_LIST_ERROR = "GET_PATIENT_LIST_ERROR"

export const GET_PATIENT_REGISTRATION_REQUEST = "GET_PATIENT_REGISTRATION_REQUEST"
export const GET_PATIENT_REGISTRATION_SUCCESS = "GET_PATIENT_REGISTRATION_SUCCESS"
export const GET_PATIENT_REGISTRATION_ERROR = "GET_PATIENT_REGISTRATION_ERROR"

export const GET_PATIENT_EDIT_REQUEST = "GET_PATIENT_EDIT_REQUEST"
export const GET_PATIENT_EDIT_SUCCESS = "GET_PATIENT_EDIT_SUCCESS"
export const GET_PATIENT_EDIT_ERROR = "GET_PATIENT_EDIT_ERROR"

export const GET_PATIENT_OUT_REQUEST = "GET_PATIENT_LIST_REQUEST"
export const GET_PATIENT_OUT_SUCCESS = "GET_PATIENT_LIST_SUCCESS"
export const GET_PATIENT_OUT_ERROR = "GET_PATIENT_LIST_ERROR"

export const GET_NEXT_VISIT_REQUEST = "GET_NEXT_VISIT_REQUEST"
export const GET_NEXT_VISIT_SUCCESS = "GET_NEXT_VISIT_SUCCESS"
export const GET_NEXT_VISIT_ERROR = "GET_NEXT_VISIT_ERROR"

export const GET_VISIT_LIST_REQUEST = "GET_VISIT_LIST_REQUEST"
export const GET_VISIT_LIST_SUCCESS = "GET_VISIT_LIST_SUCCESS"
export const GET_VISIT_LIST_ERROR = "GET_VISIT_LIST_ERROR"

export const GET_ADD_VISIT_REQUEST = "GET_ADD_VISIT_REQUEST"
export const GET_ADD_VISIT_SUCCESS = "GET_ADD_VISIT_SUCCESS"
export const GET_ADD_VISIT_ERROR = "GET_ADD_VISIT_ERROR"

export const GET_EDUCATOR_MSG_LIST_REQUEST = "GET_EDUCATOR_MSG_LIST_REQUEST"
export const GET_EDUCATOR_MSG_LIST_SUCCESS = "GET_EDUCATOR_MSG_LIST_SUCCESS"
export const GET_EDUCATOR_MSG_LIST_ERROR = "GET_EDUCATOR_MSG_LIST_ERROR"

export const GET_CATEGORY_LIST_REQUEST = "GET_CATEGORY_LIST_REQUEST"
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS"
export const GET_CATEGORY_LIST_ERROR = "GET_CATEGORY_LIST_ERROR"

export const GET_KNOWLEDGE_LIST_REQUEST = "GET_KNOWLEDGE_LIST_REQUEST"
export const GET_KNOWLEDGE_LIST_SUCCESS = "GET_KNOWLEDGE_LIST_SUCCESS"
export const GET_KNOWLEDGE_LIST_ERROR = "GET_KNOWLEDGE_LIST_ERROR"

export const GET_STATE_LIST_REQUEST = "GET_STATE_LIST_REQUEST"
export const GET_STATE_LIST_SUCCESS = "GET_STATE_LIST_SUCCESS"
export const GET_STATE_LIST_ERROR = "GET_STATE_LIST_ERROR"

export const GET_COUNTRY_LIST_REQUEST = "GET_COUNTRY_LIST_REQUEST"
export const GET_COUNTRY_LIST_SUCCESS = "GET_COUNTRY_LIST_SUCCESS"
export const GET_COUNTRY_LIST_ERROR = "GET_COUNTRY_LIST_ERROR"

export const GET_PLAN_LIST_REQUEST = "GET_PLAN_LIST_REQUEST"
export const GET_PLAN_LIST_SUCCESS = "GET_PLAN_LIST_SUCCESS"
export const GET_PLAN_LIST_ERROR = "GET_PLAN_LIST_ERROR"

export const UPLOAD_FILE_REQUEST = "UPLOAD_FILE_REQUEST"
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS"
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR"

export const GET_TREATMENT_WITH_TYPES_REQUEST = "GET_TREATMENT_WITH_TYPES_REQUEST"
export const GET_TREATMENT_WITH_TYPES_SUCCESS = "GET_TREATMENT_WITH_TYPES_SUCCESS"
export const GET_TREATMENT_WITH_TYPES_ERROR = "GET_TREATMENT_WITH_TYPES_ERROR"

export const GET_UNIT_LIST_REQUEST = "GET_UNIT_LIST_REQUEST"
export const GET_UNIT_LIST_SUCCESS = "GET_UNIT_LIST_SUCCESS"
export const GET_UNIT_LIST_ERROR = "GET_UNIT_LIST_ERROR"

export const GET_TIME_LIST_REQUEST = "GET_TIME_LIST_REQUEST"
export const GET_TIME_LIST_SUCCESS = "GET_TIME_LIST_SUCCESS"
export const GET_TIME_LIST_ERROR = "GET_TIME_LIST_ERROR"

//Diet
export const GET_DIET_LIST_SUCCESS = "GET_DIET_LIST_SUCCESS"
export const GET_DIET_LIST_ERROR = "GET_DIET_LIST_ERROR"

export const PRINT_DIET_REQUEST = "PRINT_DIET_REQUEST"
export const PRINT_DIET_SUCCESS = "PRINT_DIET_SUCCESS"
export const PRINT_DIET_ERROR = "PRINT_DIET_ERROR"

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST"
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS"
export const ADD_TASK_ERROR = "ADD_TASK_ERROR"


export const PRINT_SHARE_DOCUMENT_REQUEST = "PRINT_SHARE_DOCUMENT_REQUEST"
export const PRINT_SHARE_DOCUMENT_SUCCESS = "PRINT_SHARE_DOCUMENT_SUCCESS"
export const PRINT_SHARE_DOCUMENT_ERROR = "PRINT_SHARE_DOCUMENT_ERROR"

export const GET_TASK_LIST_REQUEST = "GET_TASK_LIST_REQUEST"
export const GET_TASK_LIST_SUCCESS = "GET_TASK_LIST_SUCCESS"
export const GET_TASK_LIST_ERROR = "GET_TASK_LIST_ERROR"

export const ADD_FAQ_REQUEST = "ADD_FAQ_REQUEST"
export const ADD_FAQ_SUCCESS = "ADD_FAQ_SUCCESS"
export const ADD_FAQ_ERROR = "ADD_FAQ_ERROR"

export const UPLOAD_MULTIFILE_REQUEST = "UPLOAD_MULTIFILE_REQUEST"
export const UPLOAD_MULTIFILE_SUCCESS = "UPLOAD_MULTIFILE_SUCCESS"
export const UPLOAD_MULTIFILE_ERROR = "UPLOAD_MULTIFILE_ERROR"

export const ADD_KNOWLEDGE_REQUEST = "ADD_KNOWLEDGE_REQUEST"
export const ADD_KNOWLEDGE_SUCCESS = "ADD_KNOWLEDGE_SUCCESS"
export const ADD_KNOWLEDGE_ERROR = "ADD_KNOWLEDGE_ERROR"

export const ADD_CLINIC_LINK_REQUEST = "ADD_CLINIC_LINK_REQUEST"
export const ADD_CLINIC_LINK_SUCCESS = "ADD_CLINIC_LINK_SUCCESS"
export const ADD_CLINIC_LINK_ERROR = "ADD_CLINIC_LINK_ERROR"

export const ADD_EDUCATOR_MSG_REQUEST = "ADD_EDUCATOR_MSG_REQUEST"
export const ADD_EDUCATOR_MSG_SUCCESS = "ADD_EDUCATOR_MSG_SUCCESS"
export const ADD_EDUCATOR_MSG_ERROR = "ADD_EDUCATOR_MSG_ERROR"

export const GET_USER_LIST_REQUEST = "GET_USER_LIST_REQUEST"
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS"
export const GET_USER_LIST_ERROR = "GET_USER_LIST_ERROR"

export const CHANGE_STATUS_REQUEST = "CHANGE_STATUS_REQUEST"
export const CHANGE_STATUS_SUCCESS = "CHANGE_STATUS_SUCCESS"
export const CHANGE_STATUS_ERROR = "CHANGE_STATUS_ERROR"

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR"

export const ADD_CLINIC_HOLIDAY_REQUEST = "ADD_CLINIC_HOLIDAY_REQUEST"
export const ADD_CLINIC_HOLIDAY_SUCCESS = "ADD_CLINIC_HOLIDAY_SUCCESS"
export const ADD_CLINIC_HOLIDAY_ERROR = "ADD_CLINIC_HOLIDAY_ERROR"

export const CHAT_USER_LIST_REQUEST = "CHAT_USER_LIST_REQUEST"
export const CHAT_USER_LIST_SUCCESS = "CHAT_USER_LIST_SUCCESS"
export const CHAT_USER_LIST_ERROR = "CHAT_USER_LIST_ERROR"

export const GET_PATIENT_CHAT_REQUEST = "GET_PATIENT_CHAT_REQUEST"
export const GET_PATIENT_CHAT_SUCCESS = "GET_PATIENT_CHAT_SUCCESS"
export const GET_PATIENT_CHAT_ERROR = "GET_PATIENT_CHAT_ERROR"

export const GET_SPECIALIZATIONS_REQUEST = "GET_SPECIALIZATIONS_REQUEST"
export const GET_SPECIALIZATIONS_SUCCESS = "GET_SPECIALIZATIONS_SUCCESS"
export const GET_SPECIALIZATIONS_ERROR = "GET_SPECIALIZATIONS_ERROR"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"

export const CHANGE_USER_STATUS_REQUEST = "CHANGE_USER_STATUS_REQUEST"
export const CHANGE_USER_STATUS_SUCCESS = "CHANGE_USER_STATUS_SUCCESS"
export const CHANGE_USER_STATUS_ERROR = "CHANGE_USER_STATUS_ERROR"

export const HISTORY_REQUEST = "HISTORY_REQUEST"
export const HISTORY_SUCCESS = "HISTORY_SUCCESS"
export const HISTORY_ERROR = "HISTORY_ERROR"

export const FORWARD_CHAT_REQUEST = "FORWARD_CHAT_REQUEST"
export const FORWARD_CHAT_SUCCESS = "FORWARD_CHAT_SUCCESS"
export const FORWARD_CHAT_ERROR = "FORWARD_CHAT_ERROR"

export const GET_CHAT_COUNT_REQUEST = "GET_CHAT_COUNT_REQUEST"
export const GET_CHAT_COUNT_SUCCESS = "GET_CHAT_COUNT_SUCCESS"
export const GET_CHAT_COUNT_ERROR = "GET_CHAT_COUNT_ERROR"

export const READ_CHAT_REQUEST = "READ_CHAT_REQUEST"
export const READ_CHAT_SUCCESS = "READ_CHAT_SUCCESS"
export const READ_CHAT_ERROR = "READ_CHAT_ERROR"


